"""Generates the Draft 0.1 cross-implementation interoperability report.

Runs both reference implementations against the shared fixture corpus in
`interop/fixtures/` and the canonical-hash-parity check, then writes
`interop/INTEROPERABILITY_REPORT.md` from the actual results. The report is
generated, not hand-maintained, so it cannot silently drift from what the two
implementations actually do; re-run this script whenever either
implementation or the fixture corpus changes.

See ATMANATIC_PROTOCOL_0.1_DRAFT.md section 14 and
ATMANATIC_MASTER_IMPLEMENTATION_ROADMAP.md Step 8.
"""

from __future__ import annotations

import json
import platform
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from interop.verify_fixtures import FIXTURES_DIR, collect_results  # noqa: E402

REFERENCE_TS_DIR = REPO_ROOT / "interop" / "reference-ts"
REPORT_PATH = REPO_ROOT / "interop" / "INTEROPERABILITY_REPORT.md"


class ReportGenerationError(RuntimeError):
    """Raised when a reference implementation cannot be run to produce results."""


def _run_typescript_check() -> dict[str, object]:
    build = subprocess.run(
        ["npm", "run", "build"],
        cwd=REFERENCE_TS_DIR,
        capture_output=True,
        text=True,
        shell=(sys.platform == "win32"),
    )
    if build.returncode != 0:
        raise ReportGenerationError(f"TypeScript build failed:\n{build.stdout}\n{build.stderr}")

    result = subprocess.run(
        ["node", "dist/src/checkFixtures.js"],
        cwd=REFERENCE_TS_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise ReportGenerationError(f"TypeScript fixture check failed:\n{result.stderr}")
    return json.loads(result.stdout)


def _node_version() -> str:
    result = subprocess.run(["node", "--version"], capture_output=True, text=True)
    return result.stdout.strip()


def _row_agrees(python_row: dict[str, object], ts_row: dict[str, object] | None) -> bool:
    if ts_row is None:
        return False
    if python_row["expected_verdict"] != ts_row.get("actual_verdict"):
        return False
    if python_row["expected_verdict"] == "reject" and python_row.get("expected_code"):
        return python_row["expected_code"] == ts_row.get("actual_code")
    return True


def generate() -> str:
    python_results = collect_results()
    ts_output = _run_typescript_check()
    ts_by_case = {row["case_id"]: row for row in ts_output["results"]}

    parity = json.loads((FIXTURES_DIR / "canonical_hash_parity.json").read_text(encoding="utf-8"))
    from atmanatic_research import compute_content_hash  # local import: only needed for the report

    python_hash = compute_content_hash(parity["record"])
    ts_parity = ts_output["canonical_hash_parity"]

    total = len(python_results)
    agreements = 0
    rows: list[str] = []
    for row in python_results:
        ts_row = ts_by_case.get(row["case_id"])
        agrees = _row_agrees(row, ts_row)
        agreements += int(agrees)

        expected_display = (
            "accept" if row["expected_verdict"] == "accept" else f"reject ({row.get('expected_code')})"
        )
        python_display = (
            "accept" if row["actual_verdict"] == "accept" else f"reject ({row.get('actual_code')})"
        )
        if ts_row is None:
            ts_display = "MISSING"
        elif ts_row.get("actual_verdict") == "accept":
            ts_display = "accept"
        else:
            ts_display = f"reject ({ts_row.get('actual_code')})"

        rows.append(
            f"| {row['case_id']} | {row['artifact_type']} | {expected_display} | "
            f"{python_display} | {ts_display} | {'yes' if agrees else '**NO**'} |"
        )

    generated_at = datetime.now(timezone.utc).isoformat()
    lines = [
        "# Atmanatic Protocol 0.1 Interoperability Report",
        "",
        f"Generated: {generated_at}",
        f"Python: {platform.python_version()} ({platform.system()})",
        f"Node: {_node_version()}",
        "",
        "This report is generated by `interop/generate_report.py`, which runs both",
        "reference implementations against the shared fixture corpus in",
        "`interop/fixtures/` and reports what actually happened. It is not",
        "hand-maintained and should be regenerated whenever either implementation",
        "or the fixture corpus changes.",
        "",
        "## Summary",
        "",
        f"- Fixtures checked: {total}",
        f"- Implementations agreeing (verdict + error code): {agreements}/{total}",
        f"- Canonical hash parity: {'MATCH' if ts_parity['matches'] and python_hash == parity['expected_sha256'] else 'MISMATCH'}"
        f" (expected `{parity['expected_sha256']}`, Python got `{python_hash}`, TypeScript got `{ts_parity['actual_sha256']}`)",
        "",
        "## Per-fixture results",
        "",
        "| Case | Type | Expected | Python | TypeScript | Agree |",
        "| --- | --- | --- | --- | --- | --- |",
        *rows,
        "",
        "## Scope",
        "",
        "Covered by both implementations: the common artifact envelope, evidence",
        "cards, proposal envelopes, review outcomes, verification results,",
        "promotion records, and canonical content-hash computation.",
        "",
        "Not covered by the TypeScript implementation (Python-only): source",
        "policy, evidence admission, orchestration/referee loops, lifecycle",
        "events, and graph analysis (the last is explicitly non-core per",
        "ATMANATIC_PROTOCOL_0.1_DRAFT.md section 18).",
        "",
    ]
    if agreements != total:
        lines.insert(
            0,
            "> **WARNING: this report was generated with at least one disagreement "
            "between implementations. See the per-fixture table below.**\n",
        )
    return "\n".join(lines)


def main() -> int:
    report = generate()
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"wrote {REPORT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
